### ISSUE TITLE
Pipeline dependency error / shared library error + workaround

### ISSUE THREAD

**Issue by 2iut128374gb21563** [nicwulab/SARS-CoV-2_in_vitro_adaptation#2]
Short workaround that worked for me:
```
conda install -c bioconda samtools==1.11
conda remove pysam
pip install --no-cache-dir pysam
conda install tbb=2020.2
```

When running `snakemake -s pipeline.smk` after setting up a fresh environment using conda as mentioned in README.md i get following error:
**samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory**

> rule align_with_bowtie:
>     input: /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/trimmed.fq.gz
>     output: /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/aligned.bam
>     jobid: 8
>     wildcards: SAMPLENAME=SRR13563354_1
> 
> samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
> Error in job align_with_bowtie while creating output file /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/aligned.bam.
> RuleException:
> CalledProcessError in line 188 of /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/codes/pipeline.smk:
> Command 'bowtie2 -x /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/ref/Bavtpat1_complete.fa --no-discordant --dovetail --no-mixed --maxins 2000 --interleaved /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/trimmed.fq.gz --mm | samtools view -bF 4  > /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/aligned.bam' returned non-zero exit status 127.
>   File "/home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/codes/pipeline.smk", line 188, in __rule_align_with_bowtie
>   File "/home/david/miniconda3/envs/SARS_master/lib/python3.6/concurrent/futures/thread.py", line 56, in run
> Removing output files of failed job align_with_bowtie since they might be corrupted:
> /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/aligned.bam
> Will exit after finishing currently running jobs.
> Exiting because a job execution failed. Look above for error message

solution:
`conda install -c bioconda samtools==1.11`

Then following error occurs:
**ImportError: libhts.so.2: cannot open shared object file: No such file or directory**

> rule cal_frequency:
>     input: /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/sorted.bam
>     output: /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/MBCS_seqlogo.png, /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/MBCS_freq.tsv
>     jobid: 4
>     wildcards: SAMPLENAME=SRR13563354_1
> 
> Traceback (most recent call last):
>   File "/home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/codes/extract_MBCS.py", line 3, in <module>
>     import pysam
>   File "/home/david/miniconda3/envs/SARS_master/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
>     from pysam.libchtslib import *
> ImportError: libhts.so.2: cannot open shared object file: No such file or directory
> Error in job cal_frequency while creating output files /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/MBCS_seqlogo.png, /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/MBCS_freq.tsv.
> RuleException:
> CalledProcessError in line 120 of /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/codes/pipeline.smk:
> Command 'python /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/codes/extract_MBCS.py /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/sorted.bam /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/MBCS_freq.tsv /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/MBCS_seqlogo.png' returned non-zero exit status 1.
>   File "/home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/codes/pipeline.smk", line 120, in __rule_cal_frequency
>   File "/home/david/miniconda3/envs/SARS_master/lib/python3.6/concurrent/futures/thread.py", line 56, in run
> Will exit after finishing currently running jobs.
> Exiting because a job execution failed. Look above for error message

solution:
```
conda remove pysam
pip install --no-cache-dir pysam
```

Then following error occurs:
**error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory**

> rule align_with_bowtie:
>     input: /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/trimmed.fq.gz
>     output: /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/aligned.bam
>     jobid: 8
>     wildcards: SAMPLENAME=SRR13563354_1
> 
> /home/david/miniconda3/envs/SARS_master/bin/bowtie2-align-s: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
> (ERR): Description of arguments failed!
> Exiting now ...
> [main_samview] fail to read the header from "-".
> Error in job align_with_bowtie while creating output file /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/aligned.bam.
> RuleException:
> CalledProcessError in line 188 of /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/codes/pipeline.smk:
> Command 'bowtie2 -x /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/ref/Bavtpat1_complete.fa --no-discordant --dovetail --no-mixed --maxins 2000 --interleaved /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/trimmed.fq.gz --mm | samtools view -bF 4  > /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/aligned.bam' returned non-zero exit status 1.
>   File "/home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/codes/pipeline.smk", line 188, in __rule_align_with_bowtie
>   File "/home/david/miniconda3/envs/SARS_master/lib/python3.6/concurrent/futures/thread.py", line 56, in run
> Removing output files of failed job align_with_bowtie since they might be corrupted:
> /home/david/nicwulab/SARS-CoV-2_in_vitro_adaptation/results/SRR13563354_1/aligned.bam
> Will exit after finishing currently running jobs.
> Exiting because a job execution failed. Look above for error message

solution:
`conda install tbb=2020.2`

After that, pipeline.smk successfully completes.
Hope this is helpful to somebody. I got this error right after creating a fresh environment using conda. Please let me know if i did something wrong in the first place, thank you!

**Comment by wckdouglas** [comment]
@2iut128374gb21563 Thank you very much for providing the solution! I agree conda has been getting a little flaky now and is not as reproducible as we'd like. Many of the packages can be depending on the conda-channels and the OS, which things can get hairy easily. 

In our [CI](https://github.com/nicwulab/SARS-CoV-2_in_vitro_adaptation/blob/develop/.github/workflows/test_env.yml) script, we do the following for a ubuntu machine:

```
conda install -c conda-forge mamba          
mamba install -c bioconda -c anaconda python=3.6 cutadapt bowtie2 samtools snakemake pandas varscan bamutil seqtk mosdepth matplotlib pandas logomaker seaborn pytest          
pip install pysam
``` 

Another alternative can be using this [conda env file](https://github.com/nicwulab/UK_strain_in_vitro_fitness/blob/main/env.yml) file, but I guess it also depend on the OS.
