### ISSUE TITLE
QUESTION: Provided results in /results non-reproducible

### ISSUE THREAD

**Issue by 2iut128374gb21563** [nicwulab/SARS-CoV-2_in_vitro_adaptation#3]
Hello,
i tried to reproduce your results using your pipeline and public SRA records, but there are minor differences.
For example when i run sample P28 (SRR13563355 in Sequence Read Archive) through your pipeline, i get the following variants.snp output: 

[variants_P28.snp.txt](https://github.com/nicwulab/SARS-CoV-2_in_vitro_adaptation/files/6642057/variants_P28.snp.txt)

> Chrom	Position	Ref	Cons	Reads1	Reads2	VarFreq	Strands1	Strands2	Qual1	Qual2	Pvalue	MapQual1	MapQual2	Reads1Plus	Reads1Minus	Reads2Plus	Reads2Minus	VarAllele
> BavtPat1.fa	1813	T	*/+A	768	8	1.02%	2	1	37	37	0.0038360719800150152	1	1	712	56	8	0	+A
> BavtPat1.fa	1912	C	Y	705	18	2.49%	2	1	37	37	3.427233201087404E-6	1	1	695	10	18	0	T
> BavtPat1.fa	2599	G	K	168	6	3.45%	2	1	41	37	0.014955435339687276	1	1	147	21	6	0	T
> BavtPat1.fa	3047	G	K	280	6	2.1%	2	2	59	60	0.015216698763722425	1	1	227	53	4	2	T
> BavtPat1.fa	3778	A	R	599	7	1.16%	2	2	39	42	0.0076775829420487485	1	1	35	564	1	6	G
> BavtPat1.fa	4893	C	Y	459	5	1.08%	2	2	39	45	0.030913437709528726	1	1	101	358	1	4	T
> BavtPat1.fa	6696	C	*/+T	446	9	1.97%	2	2	39	46	0.0018766656885966895	1	1	401	45	8	1	+T
> BavtPat1.fa	8668	C	Y	505	6	1.17%	2	2	39	38	0.015396121242459386	1	1	292	213	2	4	T
> BavtPat1.fa	11173	C	Y	144	5	3.36%	2	2	40	37	0.030203161559086377	1	1	81	63	3	2	T
> BavtPat1.fa	17999	C	Y	357	18	4.8%	2	2	66	68	3.0955569052562397E-6	1	1	341	16	16	2	T
> BavtPat1.fa	18412	G	*/-TT	656	12	1.8%	2	1	61	72	2.3227305687118882E-4	1	1	540	116	12	0	-TT
> BavtPat1.fa	18824	A	R	1325	15	1.12%	2	2	39	39	2.5061819208955014E-4	1	1	1051	274	12	3	G
> BavtPat1.fa	19208	A	R	1136	22	1.9%	2	2	37	37	2.609751150390389E-6	1	1	227	909	6	16	G
> BavtPat1.fa	19727	A	M	4941	52	1.04%	2	2	37	38	4.911220812049726E-12	1	1	554	4387	1	51	C
> BavtPat1.fa	19983	C	*/+T	495	8	1.56%	2	2	39	41	0.003798231318649962	1	1	105	390	2	6	+T
> BavtPat1.fa	21101	G	*/+T	440	8	1.79%	2	2	41	51	0.0037850673649748043	1	1	265	175	6	2	+T
> BavtPat1.fa	22206	A	R	127	5	3.79%	2	1	58	70	0.030068615882161517	1	1	111	16	5	0	G
> BavtPat1.fa	23618	A	R	637	763	54.5%	2	2	68	64	3.4438440520401225E-291	1	1	625	12	753	10	G
> BavtPat1.fa	26895	C	Y	472	8	1.67%	2	2	61	58	0.0037930908510905733	1	1	357	115	6	2	T
> BavtPat1.fa	27380	T	*/+C	86	10	10.42%	2	1	40	37	7.630733016589391E-4	1	1	20	66	10	0	+C
> BavtPat1.fa	27425	C	M	556	6	1.07%	2	1	38	37	0.015416854001135672	1	1	496	60	6	0	A
> BavtPat1.fa	27513	C	Y	508	12	2.31%	2	2	38	40	2.289656400273516E-4	1	1	486	22	11	1	T
> BavtPat1.fa	28253	C	*/-A	820	10	1.19%	2	1	61	30	9.502965933816853E-4	1	1	764	56	10	0	-A
> BavtPat1.fa	28709	A	*/-T	276	7	2.47%	2	2	39	43	0.007524698125609518	1	1	70	206	6	1	-T
> BavtPat1.fa	29229	G	S	1216	19	1.54%	2	2	38	44	1.8808797083552953E-5	1	1	1112	104	4	15	C
> BavtPat1.fa	29263	G	*/+TTT	1302	25	1.88%	2	1	64	37	3.6211093639379913E-7	1	1	1178	124	0	25	+TTT
> BavtPat1.fa	29313	A	R	1244	13	1.03%	2	2	67	59	8.914180950412586E-4	1	1	1144	100	12	1	G
> BavtPat1.fa	29324	A	*/+T	1247	17	1.34%	2	1	68	37	6.907468276592092E-5	1	1	1157	90	0	17	+T
> BavtPat1.fa	29685	T	*/+CGGGCA	667	57	7.82%	2	1	66	36	2.2030956399812824E-18	1	1	608	59	57	0	+CGGGCA
> BavtPat1.fa	29708	C	*/+TT	463	27	5.5%	2	1	38	37	5.155825361222402E-9	1	1	2	461	0	27	+TT
> BavtPat1.fa	29766	G	*/+C	289	6	2.02%	1	1	37	33	0.015229112301206745	1	1	0	289	0	6	+C
> BavtPat1.fa	29787	C	*/+CTAAACTT	250	7	2.72%	1	1	37	37	0.007495813166417644	1	1	0	250	0	7	+CTAAACTT
> BavtPat1.fa	29794	G	K	226	5	2.16%	1	1	38	36	0.030574341088559838	1	1	0	226	0	5	T

When comparing these to your own provided results in /results/P28_S28/variants.snp, as you can see, the number of identified SNVs is different and some other values like number of supporting reads, variant allele frequency etc. is also varying.

Can you confirm this? I guess this is due to some parameter tweaking after the results were published?
Feel free to close/remove this comment if it is not appropriate.
Thanks very much in advance!

**Comment by wckdouglas** [comment]
Hi @2iut128374gb21563, you are absolutely correct that the uploaded snp files are from an earlier iteration of the experiment, we have now replaced the files with the latest ones that we used in the paper. Thank you for identified the problem in the repo!

**Comment by 2iut128374gb21563** [comment]
@wckdouglas Thank you very much for sorting this out!
